name: RNA-FM
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - biopython=1.83
  - pandas=2.0.3
  - pillow=10.4.0
  - python=3.8
  - pytorch-ignite=0.4.8
  - pytorch=1.9
  - numpy=1.24.4
  - scikit-learn=1.3.2
  - tqdm
  - pip:
    - ptflops==0.7.3
    - yacs==0.1.8